- name: Install gogs
  hosts: all
  become: yes
  vars:
    gogs_use_mysql: yes
    gogs_db_username: gogs_db
    gogs_db_password: gogs_db

  pre_tasks:
    - name: Ensure build dependencies are installed.
      package: name=curl state=present
      tags: ['install']

  tasks: 
    - include_role:
        name: "{{ item }}"
      with_items: 
        - geerlingguy.git
        - geerlingguy.mysql
        - geerlingguy.gogs
      tags: ['install']

  post_tasks:
    - include_tasks: "tests/test_main_included.yml"
      tags: ['test']
    - import_tasks: "tests/test_main_imported.yml"
      tags: ['test']
    - import_tasks: "tests/test_main.yml"
      tags: ['test']
